# TCL File Generated by Component Editor 18.1
# Thu May 05 20:47:34 CDT 2022
# DO NOT MODIFY


# 
# VGA_text_mode_controller "VGA Text Mode Controller" v2.0
# Wesley Wu 2022.05.05.20:47:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module VGA_text_mode_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME VGA_text_mode_controller
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE 385 Custom IPs"
set_module_property AUTHOR "Wesley Wu"
set_module_property DISPLAY_NAME "VGA Text Mode Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_text_avl_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_text_avl_interface_v2.sv SYSTEM_VERILOG PATH vga_text_avl_interface_v2.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_text_avl_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_text_avl_interface_v2.sv SYSTEM_VERILOG PATH vga_text_avl_interface_v2.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point avl_mm_slave
# 
add_interface avl_mm_slave avalon end
set_interface_property avl_mm_slave addressUnits WORDS
set_interface_property avl_mm_slave associatedClock CLK
set_interface_property avl_mm_slave associatedReset RESET
set_interface_property avl_mm_slave bitsPerSymbol 8
set_interface_property avl_mm_slave burstOnBurstBoundariesOnly false
set_interface_property avl_mm_slave burstcountUnits WORDS
set_interface_property avl_mm_slave explicitAddressSpan 0
set_interface_property avl_mm_slave holdTime 0
set_interface_property avl_mm_slave linewrapBursts false
set_interface_property avl_mm_slave maximumPendingReadTransactions 0
set_interface_property avl_mm_slave maximumPendingWriteTransactions 0
set_interface_property avl_mm_slave readLatency 0
set_interface_property avl_mm_slave readWaitTime 1
set_interface_property avl_mm_slave setupTime 0
set_interface_property avl_mm_slave timingUnits Cycles
set_interface_property avl_mm_slave writeWaitTime 0
set_interface_property avl_mm_slave ENABLED true
set_interface_property avl_mm_slave EXPORT_OF ""
set_interface_property avl_mm_slave PORT_NAME_MAP ""
set_interface_property avl_mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property avl_mm_slave SVD_ADDRESS_GROUP ""

add_interface_port avl_mm_slave AVL_ADDR address Input 12
add_interface_port avl_mm_slave AVL_BYTE_EN byteenable Input 4
add_interface_port avl_mm_slave AVL_CS chipselect Input 1
add_interface_port avl_mm_slave AVL_READ read Input 1
add_interface_port avl_mm_slave AVL_READDATA readdata Output 32
add_interface_port avl_mm_slave AVL_WRITE write Input 1
add_interface_port avl_mm_slave AVL_WRITEDATA writedata Input 32
set_interface_assignment avl_mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avl_mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avl_mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avl_mm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point VGA_port
# 
add_interface VGA_port conduit end
set_interface_property VGA_port associatedClock CLK
set_interface_property VGA_port associatedReset ""
set_interface_property VGA_port ENABLED true
set_interface_property VGA_port EXPORT_OF ""
set_interface_property VGA_port PORT_NAME_MAP ""
set_interface_property VGA_port CMSIS_SVD_VARIABLES ""
set_interface_property VGA_port SVD_ADDRESS_GROUP ""

add_interface_port VGA_port blue blue Output 4
add_interface_port VGA_port green green Output 4
add_interface_port VGA_port red red Output 4
add_interface_port VGA_port hs hs Output 1
add_interface_port VGA_port vs vs Output 1


# 
# connection point keyboard
# 
add_interface keyboard conduit end
set_interface_property keyboard associatedClock CLK
set_interface_property keyboard associatedReset ""
set_interface_property keyboard ENABLED true
set_interface_property keyboard EXPORT_OF ""
set_interface_property keyboard PORT_NAME_MAP ""
set_interface_property keyboard CMSIS_SVD_VARIABLES ""
set_interface_property keyboard SVD_ADDRESS_GROUP ""

add_interface_port keyboard keycode keycode Input 8


# 
# connection point move_ready
# 
add_interface move_ready conduit end
set_interface_property move_ready associatedClock CLK
set_interface_property move_ready associatedReset ""
set_interface_property move_ready ENABLED true
set_interface_property move_ready EXPORT_OF ""
set_interface_property move_ready PORT_NAME_MAP ""
set_interface_property move_ready CMSIS_SVD_VARIABLES ""
set_interface_property move_ready SVD_ADDRESS_GROUP ""

add_interface_port move_ready move_hl ready Input 1


# 
# connection point win_condition
# 
add_interface win_condition conduit end
set_interface_property win_condition associatedClock CLK
set_interface_property win_condition associatedReset ""
set_interface_property win_condition ENABLED true
set_interface_property win_condition EXPORT_OF ""
set_interface_property win_condition PORT_NAME_MAP ""
set_interface_property win_condition CMSIS_SVD_VARIABLES ""
set_interface_property win_condition SVD_ADDRESS_GROUP ""

add_interface_port win_condition game_won edge Input 1


# 
# connection point game_reset
# 
add_interface game_reset conduit end
set_interface_property game_reset associatedClock CLK
set_interface_property game_reset associatedReset ""
set_interface_property game_reset ENABLED true
set_interface_property game_reset EXPORT_OF ""
set_interface_property game_reset PORT_NAME_MAP ""
set_interface_property game_reset CMSIS_SVD_VARIABLES ""
set_interface_property game_reset SVD_ADDRESS_GROUP ""

add_interface_port game_reset game_reset sig Output 1


# 
# connection point indicator
# 
add_interface indicator conduit end
set_interface_property indicator associatedClock CLK
set_interface_property indicator associatedReset ""
set_interface_property indicator ENABLED true
set_interface_property indicator EXPORT_OF ""
set_interface_property indicator PORT_NAME_MAP ""
set_interface_property indicator CMSIS_SVD_VARIABLES ""
set_interface_property indicator SVD_ADDRESS_GROUP ""

add_interface_port indicator indicator hex Output 4

